import { BellRing, Mail, MapPin, ShieldCheck, UserRound } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { DashboardLayout } from "../../components/layout/DashboardLayout";
import { DEMO_USER } from "../../constants/demoUser";
import { MOCK_COMPETITIONS } from "../../constants/mockCompetitions";

export function ProfilePage() {
  const navigate = useNavigate();
  const savedCount = MOCK_COMPETITIONS.filter((competition) => competition.isBookmarked).length;
  const goToPage = (id) => navigate(id === "bookmarks" ? "/saved" : id === "upcoming" ? "/upcoming" : id === "profile" ? "/profile" : "/discover");
  return <DashboardLayout activeNavId="profile" onNavigate={goToPage} bookmarkCount={savedCount} user={DEMO_USER} pageTitle="Your profile" pageSubtitle="A simple participant profile preview" notificationCount={3}><div className="grid gap-6 lg:grid-cols-[0.85fr_1.55fr]"><aside className="rounded-card border border-border bg-surface p-6 shadow-card sm:p-7"><div className="flex items-center gap-4"><span className="flex h-20 w-20 items-center justify-center rounded-3xl bg-sand font-display text-3xl font-bold text-bg">R</span><div><p className="font-display text-2xl font-bold text-text-primary">Rafsan Ahmed</p><p className="mt-1 flex items-center gap-1.5 text-sm text-text-muted"><MapPin size={14} /> Dhaka, Bangladesh</p></div></div><p className="mt-6 border-t border-border pt-5 text-sm leading-relaxed text-text-secondary">Building thoughtful ideas, one challenge at a time.</p><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-bg p-3"><p className="font-display text-2xl font-bold text-sand">{savedCount}</p><p className="text-xs text-text-muted">Saved items</p></div><div className="rounded-2xl bg-bg p-3"><p className="font-display text-2xl font-bold text-text-primary">12</p><p className="text-xs text-text-muted">Applications</p></div></div></aside><div className="space-y-6"><section className="rounded-card border border-border bg-surface p-5 shadow-card sm:p-7"><p className="text-xs font-bold uppercase tracking-[0.18em] text-sand">Account details</p><h2 className="mt-1 font-display text-xl font-bold text-text-primary">Personal information</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><Info icon={UserRound} label="Full name" value="Rafsan Ahmed" /><Info icon={Mail} label="Email address" value="rafsan@example.com" /><Info icon={MapPin} label="Location" value="Dhaka, Bangladesh" /></div></section><section className="rounded-card border border-border bg-surface p-5 shadow-card sm:p-7"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-danger/15 text-danger"><BellRing size={19} /></span><div><h2 className="font-display text-xl font-bold text-text-primary">Notifications</h2><p className="text-sm text-text-muted">Deadline reminders and new opportunity updates.</p></div></div></section><section className="flex items-center gap-3 rounded-card border border-sand/20 bg-sand/5 p-5"><ShieldCheck className="shrink-0 text-sand" size={25} /><p className="text-sm text-text-secondary">This is a UI-only profile page for the Catalyst design.</p></section></div></div></DashboardLayout>;
}

function Info({ icon: Icon, label, value }) { return <div><p className="flex items-center gap-1.5 text-xs font-semibold text-text-muted"><Icon size={13} /> {label}</p><p className="mt-2 rounded-xl border border-border bg-bg px-3.5 py-3 text-sm text-text-primary">{value}</p></div>; }
